name: Build and Push

on:
  push:
    branches:
      - master
      - main

jobs:
  release-and-push:
    name: Release And Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Push to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          target: STANDARD
          platforms: linux/amd64
          push: true
          tags: |
            levy001/casdoor:${{ steps.semantic.outputs.new_release_version }}
            levy001/casdoor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push All In One Version to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ALLINONE
          platforms: linux/amd64
          push: true
          tags: |
            levy001/casdoor-all-in-one:${{ steps.semantic.outputs.new_release_version }}
            levy001/casdoor-all-in-one:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max